#!/bin/zsh
# Mac OS Catalina Development Environment Setup
# https://github.com/donleemalacad/macos-catalina-dev-setup
#
# Copyright (c) Donlee Rey Malacad

ERROR_MESSAGE="\033[91m%b\033[39m"
set -euo pipefail

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until setup has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

help_text() {
cat <<EOF
    Usage: setup [OPTIONS]
    OPTION          MEANING
    --help          Display this help message
EOF
}

show_error() {
    help_text
    printf "${ERROR_MESSAGE}" "\nError: "
    printf "Illegal option!\n"
}

# Parse setup parameters
while [[ "${#}" -gt 0 ]]; do
    case "${1}" in
        --help)
            help_text
            exit 0
            ;;
        --|-*|*)
            show_error "${1}"
            exit 1
            ;;
    esac
done